# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ry-95St27SwNj2SCugUojyniqnWeMlfw
"""

import pandas as pd
data = pd.read_csv('calles_de_medellin_con_acoso.csv', sep=';').values
print(data)